"""add about info fields to agent

Revision ID: 9246efa23a0f
Revises: efacf88c0286
Create Date: 2025-12-18 15:44:53.724944

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '9246efa23a0f'
down_revision = 'efacf88c0286'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('current_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('agent', sa.Column('uptime', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('agent', sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'mac_address')
    op.drop_column('agent', 'uptime')
    op.drop_column('agent', 'current_ip')
    # ### end Alembic commands ###