"""add current_ip to agent

Revision ID: c915a25b24c1
Revises: 9246efa23a0f
Create Date: 2025-12-19 11:03:24.464820

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'c915a25b24c1'
down_revision = '9246efa23a0f'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('capture_interval', sa.Integer(), nullable=True))
    op.alter_column('camera', 'rtsp_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('camera', 'zone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('camera', 'last_snapshot',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using="last_snapshot::timestamp without time zone")  # THÊM DÒNG NÀY
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camera', 'last_snapshot',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="last_snapshot::varchar")
    op.alter_column('camera', 'zone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('camera', 'rtsp_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('camera', 'capture_interval')
    # ### end Alembic commands ###